server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false     #是否注册进注册中心
    fetch-registry: false           #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #设置与EurekaServer 交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://eureka7002.com:7002/eureka/    #集群，指向其他eureka
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    #单机版，指向自己
#  server:
#  #关闭自我保护机制，保证不可用服务被及时踢除
#  enable-self-preservation: false
#  eviction-interval-timer-in-ms: 2000